### ISSUE TITLE
[Crash] Opening a book and quill crashes the game

### ISSUE THREAD

**Issue by Kiryonn** [BluSpring/EnhancedBookWriting#1]
| | version |
|---|---|
| Minecraft | 1.20.2 |
| Loader | Fabric 0.14.24 |
| Enhanced Book Writing | 1.0.0 |

Just noticed the filename says 1.19.4 ( `EnhancedBookWriting-1.0.0+mc1.19.4` ) but ATLauncher let me donload it and the game doesn't crash either until i open a book and quill.

**Comment by BluSpring** [comment]
i would love if you provided a crash log

**Comment by Kiryonn** [comment]
I'm surprised i haven't deleted it yet. I usually do it within a few hours of the crash. Here it is:
[crash-2023-11-04_15.28.51-client.txt](https://github.com/BluSpring/EnhancedBookWriting/files/13328699/crash-2023-11-04_15.28.51-client.txt)

**Comment by BluSpring** [comment]
Fixed in aa4147af831bed12ab72b918c90bfead81ff6b46 for update v1.1.0, should be uploaded now :)
