### ISSUE TITLE
Textbook compatibility

### ISSUE THREAD

**Issue by SagiriHimoto** [BluSpring/EnhancedBookWriting#3]
Original issue is in no way related to this mod. I have no idea why I thought it was

![image](https://github.com/BluSpring/EnhancedBookWriting/assets/79280544/c3aee485-6968-459d-856d-365277417830)

**Comment by BluSpring** [comment]
EBW doesn't have an Import/Export button, what? 

EBW since v1.1.0 started using custom icon buttons instead of the conventional MC text button to avoid these kinds of issues, you may be referring to another mod.

**Comment by SagiriHimoto** [comment]
> EBW doesn't have an Import/Export button, what?
> 
> EBW since v1.1.0 started using custom icon buttons instead of the conventional MC text button to avoid these kinds of issues, you may be referring to another mod.

Oops, sorry, my b. I see now. I have too many book mods, lol
